name: mac
on: push
jobs: 
  cypress-run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install Cask
      run: brew install caskroom/cask/brew-cask
    - name: Install docker toolbox
      run: brew cask install docker-toolbox

    - name: create the docker machine
      run: docker-machine create --driver "virtualbox" myBoxName
    - name: start the docker machine
      run: docker-machine start myBoxName
    - name: Docker version
      run: docker --version  
      
    - name: docker commands
      run: eval "$(docker-machine env myBoxName)"
    - name: Build the docker-compose stack
      run: docker-compose up -d --build
