name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Backend
        run: |
          back.sh & front.sh
     
      - name: Cypress run
        uses: cypress-io/github-action@v2
