name: main
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Cypress run
        working-directory: /home/runner/work/013_vue_vuex_mongo_express/013_vue_vuex_mongo_express
        uses: cypress-io/github-action@v2