name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Backend
        run: |
          cd backend
          npm i
          npm run start
      - name: client
        run: |
          npm i
          npm run serve
         
      - name: Cypress run
        uses: cypress-io/github-action@v2
