name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker-compose stack
        uses: actions/checkout@v1
        run: docker-compose up -d --build
      - name: Cypress run
        uses: cypress-io/github-action@v2