name: main
on: push
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Cypress run
        run: |
              echo $PWD
              cd $PWD
              ls
              npx cypress run