name: ubuntuChrome
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Cypress run
        run: |
          npx cypress run --browser chrome
      - name: ZAP Scan
        run: docker run -t owasp/zap2docker-weekly zap-baseline.py -t http://localhost:8080/
      - name: Stop dockers
        run: docker-compose stop
