name: ubuntuChrome
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Cypress run
        run: |
          npx cypress run --browser chrome
          npx cypress run --browser firefox
          npx cypress run
