name: ubuntuChrome
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          docker_name: 'owasp/zap2docker-weekly'
          target: 'http://localhost:8080'
          cmd_options: '-d'
          token: ${{ secrets.GITHUB_TOKEN }}
