name: zap
on: push

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:8080/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
