name: zap
on: push

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: ZAP Scan
        run: docker run -t owasp/zap2docker-weekly zap-baseline.py -t http://localhost:8080/
      - name: Stop dockers
        run: docker-compose stop
